# coding: utf-8
require 'const/vfs_const'

module Acl
  include Vfs
  # node acl
  ACL_NODE_NO_ACCESS = 0
  ACL_NODE_READ = 1
  ACL_NODE_WRITE = 2
  ACL_NODE_DELETE = 4
  ACL_NODE_CONTROL = 8
  ACL_NODE_STICKY = 16
  
  ACL_NOTIFY_NONE = 0
  ACL_NOTIFY_IMMEDIATE = 1
  ACL_NOTIFY_DELAYED = 2
  ACL_NOTIFY_DEFAULT = ACL_NOTIFY_IMMEDIATE
  
  ACL_NODE_SUPERUSER_ACCESS = ( ACL_NODE_READ | ACL_NODE_WRITE | ACL_NODE_DELETE | ACL_NODE_CONTROL )

  ACL_NODE_FULL_ACCESS = ( ACL_NODE_READ | ACL_NODE_WRITE | ACL_NODE_DELETE | ACL_NODE_CONTROL )
  
  ACL_TYPE_DOMAIN = NODE_DIRECTORY + CONST_DOMAIN
  ACL_TYPE_DIRECTORY = NODE_DIRECTORY
  ACL_TYPE_FILE = NODE_FILE
  ACL_TYPE_SYMBOLIC_LINK = NODE_SYMBOLIC_LINK
  
  ACL_SUPER_USER_NAME = 'root'
  
  # for test
  ADMIN_SESSION_ID = "_special_administrator_session"
  
  # gid for world
  ACL_WORLD_GID = -1
  
  # uid, gid for SUPERUSER
  ACL_SUPERUSER_UID = 0
  ACL_SUPERUSER_GID = 0

  # user level
  ACL_SUPER_USER_LEVEL_X = -1
  ACL_SUPER_USER_LEVEL_Y = -1

  # not set
  ACL_NO_VALUE = -1
  
  # default acl values
  ACL_DEFAULT_UID_ACCESS_RIGHT = ( ACL_NODE_READ | ACL_NODE_WRITE | ACL_NODE_DELETE | ACL_NODE_CONTROL )
  ACL_DEFAULT_GID_ACCESS_RIGHT = ( ACL_NODE_READ | ACL_NODE_WRITE | ACL_NODE_DELETE )
  ACL_DEFAULT_WORLD_ACCESS_RIGHT = ACL_NODE_NO_ACCESS
  
  # prefix string
  ACL_PREFIX = 'spin_acl'
  
end