# SecretFiles server configuration
#
# Contents of this file are used to setup server parameters and database tables
# during server initialization.
#
#
common_params:

- &virtual_storage_server1
  host: 127.0.0.1
  port: 18880

- &virtual_thumbnail_server1
  host: 127.0.0.1
  port: 18880

- &virtual_storage_server2
  host: 127.0.0.1
  port: 18881

- &virtual_thumbnail_server2
  host: 127.0.0.1
  port: 18881

- &virtual_root_node
  node_name:  /
  hash_key: e562f69ec36e625116376f376d991e41613e9bf3

- &virtual_spin_node
  node_name:  /spin
  hash_key: 6b9fdefcd73a7854d06f98d4c930ad2b32946543

- &super_user_ids
  uid:  0
  gid:  0

config:
  # root user settings
  super_user: root
  super_user_passwd:  One4AllAll4One
  super_user_home:  *virtual_root_node
  super_user_virtual_home:  *virtual_spin_node
  super_user_id:  *super_user_ids

  # server name
  server_name:  secret_files_server

  virtual_domains:
  - #root_domain
    domain_id:  0
    domain_hash_key:  519c4b1925cbd58b618fc75063cdb5175ccfad85
    domain_name:  root
    domain_descr: "virtual root domain"
    domain_root:  *virtual_root_node
    domain_disp_name: "root domain"
    domain_link:  file_type_icon/Drawer.png
    domain_img: file_type_icon/Drawer.png
    domain_uid: 0
    domain_gid: 0
    domain_writable_status: true
    uid_access_right: 15
    gid_access_right: 7
    world_access_right: 0

  virtual_file_systems:
  - # VFS ID hash code
    # 40-byte length
    # Used to be generated by 'Security::hash_key_s(vfs_name + Time.now.to_s)'
    vfs_id: 224c4c315ca6c73e87e4ed5515dbc694ebfe24e4

    vfs_is_default: true

    # VFS name is arbitrary string
    vfs_name: "secret_files_vfs"

    # VFS storage logic
    #   METRIC under LOAD_BALANCE:
    #     ROUND_ROBIN ( default )
    #     LEAST_FILES
    #     LEAST_USAGE
    #     FASTEST ( not implemented yet, use default )
    #   SPANNING
    #   ILM
    vfs_storage_logic:  SPANNING

    # VFS types are:
    #   CLUSTER
    #   OBJECT_STORAGE_WOS
    #   OBJECT_STORAGE_S3
    #   OBJECT_STORAGE_OTHER
    #   HSM
    #     TIER1
    #     TIER2
    #     TIER3
    #     TIER0
    vfs_type: CLUSTER

    # VFS access modes
    #   READ_WRITE
    #   READ_ONLY
    #   WRITE_ONLY
    #   WRITE_ONCE
    vfs_access_mode: READ_WRITE

    # VFS attributes as HASH
    vfs_attributes: { author: "MAKEWAVE JAPAN Co., Ltd.", copyright: "2018 MAKEWAVE JAPAN Co., Ltd. All rights reserved.", service_type: "CLOUD"}

    # VFS size in GB
    # -1 to specify unlimited size
    vfs_size: -1

    # VFS max entries
    # (0..2147483647]
    # -1 to specify unlimited entries
    vfs_max_entries:  -1
  - # VFS ID hash code
    # 40-byte length
    # Used to be generated by 'Security::hash_key_s(vfs_name + Time.now.to_s)'
    vfs_id: 506565f9392c5ae008bfea8e471f2aa13c033042

    vfs_is_default: false

    # VFS name is arbitrary string
    vfs_name: "secret_files_spanning_vfs"

    # VFS storage logic
    #   METRIC under LOAD_BALANCE:
    #     ROUND_ROBIN ( default )
    #     LEAST_FILES
    #     LEAST_USAGE
    #     FASTEST ( not implemented yet, use default )
    #   SPANNING
    #   ILM
    vfs_storage_logic:  SPANNING

    # VFS types are:
    #   CLUSTER
    #   OBJECT_STORAGE_WOS
    #   OBJECT_STORAGE_S3
    #   OBJECT_STORAGE_OTHER
    #   HSM
    #     TIER1
    #     TIER2
    #     TIER3
    #     TIER0
    vfs_type: CLUSTER

    # VFS access modes
    #   READ_WRITE
    #   READ_ONLY
    #   WRITE_ONLY
    #   WRITE_ONCE
    vfs_access_mode: READ_WRITE

    # VFS attributes as HASH
    vfs_attributes: { author: 'MAKEWAVE JAPAN Co., Ltd.', copyright: '2018 MAKEWAVE JAPAN Co., Ltd. All rights reserved.', service_type: 'CLOUD'}

    # VFS size in GB
    # -1 to specify unlimited size
    vfs_size: -1

    # VFS max entries
    # (0..2147483647]
    # -1 to specify unlimited entries
    vfs_max_entries:  -1
  - # VFS ID hash code
    # 40-byte length
    # Used to be generated by 'Security::hash_key_s(vfs_name + Time.now.to_s)'
    vfs_id: 2d296f9d738c641a29d6b1fc92183200e43dde81

    vfs_is_default: false

    # VFS name is arbitrary string
    vfs_name: "secret_files_ilm_vfs"

    # VFS storage logic
    #   METRIC under LOAD_BALANCE:
    #     ROUND_ROBIN ( default )
    #     LEAST_FILES
    #     LEAST_USAGE
    #     FASTEST ( not implemented yet, use default )
    #   SPANNING
    #   ILM
    vfs_storage_logic:  ILM

    # VFS types are:
    #   CLUSTER
    #   OBJECT_STORAGE_WOS
    #   OBJECT_STORAGE_S3
    #   OBJECT_STORAGE_OTHER
    #   HSM
    #     TIER1
    #     TIER2
    #     TIER3
    #     TIER0
    vfs_type: TIER1

    # VFS access modes
    #   READ_WRITE
    #   READ_ONLY
    #   WRITE_ONLY
    #   WRITE_ONCE
    vfs_access_mode: READ_WRITE

    # VFS attributes as HASH
    vfs_attributes: { author: 'MAKEWAVE JAPAN Co., Ltd.', copyright: '2018 MAKEWAVE JAPAN Co., Ltd. All rights reserved.', service_type: 'CLOUD'}

    # VFS size in GB
    # -1 to specify unlimited size
    vfs_size: -1

    # VFS max entries
    # (0..2147483647]
    # -1 to specify unlimited entries
    vfs_max_entries:  -1
  - # VFS ID hash code
    # 40-byte length
    # Used to be generated by 'Security::hash_key_s(vfs_name + Time.now.to_s)'
    vfs_id: 1b2eab0ba8763fe80b2901b38c91b5dee44481be

    vfs_is_default: false

    # VFS name is arbitrary string
    vfs_name: "secret_files_object_storage_vfs"

    # VFS storage logic
    #   METRIC under LOAD_BALANCE:
    #     ROUND_ROBIN ( default )
    #     LEAST_FILES
    #     LEAST_USAGE
    #     FASTEST ( not implemented yet, use default )
    #   SPANNING
    #   ILM
    vfs_storage_logic:  SPANNING

    # VFS types are:
    #   CLUSTER
    #   OBJECT_STORAGE_WOS
    #   OBJECT_STORAGE_S3
    #   OBJECT_STORAGE_OTHER
    #   HSM
    #     TIER1
    #     TIER2
    #     TIER3
    #     TIER0
    vfs_type: OBJECT_STORAGE_S3

    # VFS access modes
    #   READ_WRITE
    #   READ_ONLY
    #   WRITE_ONLY
    #   WRITE_ONCE
    vfs_access_mode:  READ_WRITE

    # VFS attributes as HASH
    vfs_attributes: { author: 'MAKEWAVE JAPAN Co., Ltd.', copyright: '2018 MAKEWAVE JAPAN Co., Ltd. All rights reserved.', service_type: 'CLOUD'}

    # VFS size in GB
    # -1 to specify unlimited size
    vfs_size: -1

    # VFS max entries
    # (0..2147483647]
    # -1 to specify unlimited entries
    vfs_max_entries:  -1

  storages:
  - &storage1
    # name of this virtual storage
    storage_name: secret_files_vfs_storage1

    # vfs_id which uses this virtual storage for its file storage.
    vfs_id: 224c4c315ca6c73e87e4ed5515dbc694ebfe24e4

    # maximum size of virtual storage in GB
    # positive INTEGER or (-1) for unlimited size
    storage_group_max_size: -1

  - &storage2
    # name of this virtual storage
    storage_name: secret_files_vfs_storage2

    # vfs_id which uses this virtual storage for its file storage.
    vfs_id: 124c4c315ca6c73e87e4ed5515dbc694ebfe24e4

    # maximum size of virtual storage in GB
    # positive INTEGER or (-1) for unlimited size
    storage_group_max_size: -1

  virtual_storages:
  - # virtual file system storage server
    file_storage_server: *virtual_storage_server1
    # virtual storage server ID
    storage_id: 78aa1a92a4649278124a472a6dcb171610c145ed
    # storage info
    storage_info: *storage1
    # priority in virtual storages
    # INTEGER  0 <= P <= MAX_INTEGER
    # 0 is the highestpriority
    priority: 0
    # storage root directory
    storage_root: /webapps/spin/secret_files/spinvfs/root
    # temporary file directory
    storage_tmp:  /usr/local/var/spin/tmp
    # maximum number of directories of this virtual storage
    # positive INTEGER or (-1) for unlimited number of directories
    max_directories:  2147483647
    # maximum number of entries of this virtual storage
    # positive INTEGER or (-1) for unlimited number of entries
    max_entries:  -1
    # maximum number of entries per directory
    # positive INTEGER
    max_entries_per_directory:  1000
    # storage mapping logic
    storage_mapping_logic:  "SPANNING"
    # Storage attributes as HASH
    storage_attributes: { author: 'MAKEWAVE JAPAN Co., Ltd.', copyright: '2018 MAKEWAVE JAPAN Co., Ltd. All rights reserved.', storage_type: 'LOCAL_HDD'}

  - # virtual file system storage server
    file_storage_server: *virtual_storage_server2
    # virtual storage server ID
    storage_id: d1383b2579e852f09da87ff5002adc4d9512fb1c
    # storage info
    storage_info: *storage2
    # priority in virtual storages
    # INTEGER  0 <= P <= MAX_INTEGER
    # 0 is the highestpriority
    priority: 0
    # storage root directory
    storage_root: /webapps/spin/secret_files/spinvfs2/root
    # temporary file directory
    storage_tmp:  /usr/local/var/spin/tmp
    # maximum number of directories of this virtual storage
    # positive INTEGER or (-1) for unlimited number of directories
    max_directories:  2147483647
    # maximum number of entries of this virtual storage
    # positive INTEGER or (-1) for unlimited number of entries
    max_entries:  -1
    # maximum number of entries per directory
    # positive INTEGER
    max_entries_per_directory:  1000
    # storage mapping logic
    storage_mapping_logic:  "SPANNING"
    # Storage attributes as HASH
    storage_attributes: { author: 'MAKEWAVE JAPAN Co., Ltd.', copyright: '2018 MAKEWAVE JAPAN Co., Ltd. All rights reserved.', storage_type: 'LOCAL_HDD'}

  thumbnail_storages:
  - thumbnail_storage_server: *virtual_thumbnail_server1
    # virtual storage server ID
    storage_id: 85f43ef94c78f4d8e0f8d9472bc6cedecfd17c8b
    # storage info
    storage_info: *storage1
    # priority in virtual storages
    # INTEGER  0 <= P <= MAX_INTEGER
    # 0 is the highestpriority
    priority: 0
    # storage root directory
    storage_root: /webapps/spin/secret_files/spinvfs/root_thumbnail
    # temporary file directory
    storage_tmp:  /usr/local/var/spin/tmp
    # maximum number of directories of this virtual storage
    # positive INTEGER or (-1) for unlimited number of directories
    max_directories:  2147483647
    # maximum number of entries of this virtual storage
    # positive INTEGER or (-1) for unlimited number of entries
    max_entries:  -1
    # maximum number of entries per directory
    # positive INTEGER
    max_entries_per_directory:  1000
    # storage mapping logic
    storage_mapping_logic:  "SPANNING"
    # Storage attributes as HASH
    storage_attributes: { author: 'MAKEWAVE JAPAN Co., Ltd.', copyright: '2018 MAKEWAVE JAPAN Co., Ltd. All rights reserved.', storage_type: 'LOCAL_HDD'}
  - thumbnail_storage_server: *virtual_thumbnail_server2
    # virtual storage server ID
    storage_id: a5f43ef94c78f4d8e0f8d9472bc6cedecfd17c8b
    # storage info
    storage_info: *storage2
    # priority in virtual storages
    # INTEGER  0 <= P <= MAX_INTEGER
    # 0 is the highestpriority
    priority: 0
    # storage root directory
    storage_root: /webapps/spin/secret_files/spinvfs2/root_thumbnail
    # temporary file directory
    storage_tmp:  /usr/local/var/spin/tmp
    # maximum number of directories of this virtual storage
    # positive INTEGER or (-1) for unlimited number of directories
    max_directories:  2147483647
    # maximum number of entries of this virtual storage
    # positive INTEGER or (-1) for unlimited number of entries
    max_entries:  -1
    # maximum number of entries per directory
    # positive INTEGER
    max_entries_per_directory:  1000
    # Storage attributes as HASH
    # storage mapping logic
    storage_mapping_logic:  "SPANNING"
    storage_attributes: { author: 'MAKEWAVE JAPAN Co., Ltd.', copyright: '2018 MAKEWAVE JAPAN Co., Ltd. All rights reserved.', storage_type: 'LOCAL_HDD'}

  virtual_file_servers:
  - # ID integer
    id: 1

    # VFS server name is like "127.0.0.1:XXXX"
    vfs_server_name: cs.makewavejapan.com

    vfs_server_host_name:   cs.makewavejapan.com

    server_protocol:  http
    server_alt_protocols:  ""

    server_port:  80
    api_path: /filemanager/spin_api_request
    max_connections: -1
    max_pg_connections: -1
    receive_timeout:  3600
    send_timeout: 3600
    session_timeout:  -1
    spin_url_server_name:  http://cs.makewavejapan.com

  - # ID integer
    id: 2

    # VFS server name is like "127.0.0.1:XXXX"
    vfs_server_name: cs.makewavejapan.com:81

    vfs_server_host_name:   cs.makewavejapan.com

    server_protocol:  http
    server_alt_protocols:  ""

    server_port:  81
    api_path: /filemanager/spin_api_request
    max_connections: -1
    max_pg_connections: -1
    receive_timeout:  3600
    send_timeout: 3600
    session_timeout:  -1
    spin_url_server_name:  http://cs.makewavejapan.com:3000

